name: Cross-platform CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit
  call-windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit
  call-render-readme:
    needs: [call-linux, call-windows]
    if: >
      always() &&
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/render-readme.yml
    secrets: inherit
  call-doxygen-gh-pages:
    needs: [call-render-readme]
    uses: ./.github/workflows/doxygen-gh-pages.yml
    secrets: inherit
  call-tag-files:
    needs: [call-doxygen-gh-pages]
    uses: ./.github/workflows/tag-files.yml
    with:
      url: https://evjeesm.github.io/
    secrets: inherit
  call-static:
    needs: [call-tag-files]
    uses: ./.github/workflows/static.yml
    permissions:
      contents: read
      pages: write
      id-token: write
