name: Windows MSYS2 CI

on:
  workflow_call:
env:
  PLATFORM: Windows

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        install: >-
          curl
          git
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-check
          autotools
          autoconf-archive
          lcov

    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    - name: Regenerate build files
      run: ./autogen.sh

    - name: configure
      run: ./configure CFLAGS='-Wall -Wextra -Wno-override-init -O0 -g --coverage' --enable-code-coverage

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check
    # NO valgrind support on windows,
    # TODO: will try to use Dr. Memory, but it's not included in msys2.

    - name: Archive test logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: check-logs
        path: |
          *.log
          tests/*.log
        retention-days: 5

    - name: Run check-coverage
      run: make check-code-coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        flags: windows
        name:  Windows MSYS2 CI
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Run distcheck
      run: make distcheck

  report-status:
    runs-on: ubuntu-latest
    if: always()
    needs: [build]
    steps:
      - name: Create status badge
        run: |
          case ${{ needs.build.result }} in \
          success) echo "![status](https://img.shields.io/badge/${{ env.PLATFORM }}-passes-green)" > ${{ env.PLATFORM }}-status.md ;; \
          failure) echo "![status](https://img.shields.io/badge/${{ env.PLATFORM }}-failed-red)" > ${{ env.PLATFORM }}-status.md ;; \
          cancelled) echo "![status](https://img.shields.io/badge/${{ env.PLATFORM }}-cancelled-lightgrey)" > ${{ env.PLATFORM }}-status.md ;; \
          esac

      - name: Make status artifact name
        run: echo STATUS_NAME=${{ env.PLATFORM }}-status >> $GITHUB_ENV

      - name: Upload status badge
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.STATUS_NAME }}
          path: '*-status.md'
